CRITICAL - 2024-07-20 01:12:04 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:12:10 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:14:21 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:14:23 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:14:25 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:15:16 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:15:22 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:15:27 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:37 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:38 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:39 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:39 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:39 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:40 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:40 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:40 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:17:47 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-07-20 01:20:46 --> ErrorException: Cannot redeclare App\Controllers\Ciudadanos::nuevoCiudadano()
[Method: GET, Route: ver_ciudadanos]
in APPPATH\Controllers\Ciudadanos.php on line 18.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-07-20 01:39:43 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ci...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ci...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ci...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ci...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 01:39:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: agregar_ciudadano]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:39:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:39:43 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 01:41:16 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ci...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ci...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ci...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ci...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 01:41:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: agregar_ciudadano]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:41:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:41:16 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'120\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 01:41:19 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ci...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ci...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ci...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ci...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 01:41:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: agregar_ciudadano]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:41:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:41:19 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Ciudadanos.php(35): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 01:42:26 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ci...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ci...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ci...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ci...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 01:42:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: agregar_ciudadano]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:42:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:42:26 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`ciudadanos`, CONSTRAINT `ciudadanos_ibfk_3` FOREIGN KEY (`cod_muni`) REFERENCES `municipios` (`cod_muni`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'545645654\', \'5465454\', \'adihsah@\', \'2014-11-02\', \'5\', \'\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 01:54:02 --> CodeIgniter\HTTP\Exceptions\HTTPException: The route for "ciudadanos" cannot be found.
[Method: GET, Route: eliminar_ciudadano/858585]
in SYSTEMPATH\HTTP\RedirectResponse.php on line 64.
 1 SYSTEMPATH\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('ciudadanos')
 2 APPPATH\Controllers\Ciudadanos.php(42): CodeIgniter\HTTP\RedirectResponse->route(false)
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->eliminarCiudadano('858585')
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 02:12:11 --> mysqli_sql_exception: Duplicate entry '1212121212' for key 'PRIMARY' in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ci...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ci...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ci...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ci...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 02:12:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1212121212' for key 'PRIMARY'
[Method: POST, Route: agregar_ciudadano]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 02:12:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1212121212' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'\', \'\', \'\', \'\', \'Selecciones su Nivel Académico\', \'\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'\', \'\', \'\', \'\', \'Selecciones su Nivel Académico\', \'\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 02:12:11 --> [Caused by] mysqli_sql_exception: Duplicate entry '1212121212' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'\', \'\', \'\', \'\', \'Selecciones su Nivel Académico\', \'\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'\', \'\', \'\', \'\', \'Selecciones su Nivel Académico\', \'\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'\', \'\', \'\', \'\', \'Selecciones su Nivel Académico\', \'\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 02:12:47 --> mysqli_sql_exception: Duplicate entry '1212121212' for key 'PRIMARY' in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ci...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ci...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ci...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ci...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 02:12:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1212121212' for key 'PRIMARY'
[Method: POST, Route: agregar_ciudadano]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 02:12:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1212121212' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'556453453\', \'4354345\', \'ehwbhewbf\', \'2026-03-04\', \'6\', \'1909\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'556453453\', \'4354345\', \'ehwbhewbf\', \'2026-03-04\', \'6\', \'1909\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 02:12:47 --> [Caused by] mysqli_sql_exception: Duplicate entry '1212121212' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'556453453\', \'4354345\', \'ehwbhewbf\', \'2026-03-04\', \'6\', \'1909\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'556453453\', \'4354345\', \'ehwbhewbf\', \'2026-03-04\', \'6\', \'1909\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (\'1212121212\', \'Diaz\', \'Genesis\', \'6asdsabds\', \'556453453\', \'4354345\', \'ehwbhewbf\', \'2026-03-04\', \'6\', \'1909\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ciudadanos` (`dpi`, `apellido`, `nombre`, `direccion`, `tel_casa`, `tel_movil`, `email`, `fechanac`, `cod_nivel_acad`, `cod_muni`) VALUES (:dpi:, :apellido:, :nombre:, :direccion:, :tel_casa:, :tel_movil:, :email:, :fechanac:, :cod_nivel_acad:, :cod_muni:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Ciudadanos.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->agregarCiudadano()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 05:35:47 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`departamentos`, CONSTRAINT `departamentos_ibfk_1` FOREIGN KEY (`cod_region`) REFERENCES `regiones` (`cod_region`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `de...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `de...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `de...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `de...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Departamentos.php(28): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Departamentos->agregarDepartamento()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departamentos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 05:35:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`departamentos`, CONSTRAINT `departamentos_ibfk_1` FOREIGN KEY (`cod_region`) REFERENCES `regiones` (`cod_region`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: agregar_departamento]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (:cod_depto:, :nombre_depto:, :cod_region:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Departamentos.php(28): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Departamentos->agregarDepartamento()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departamentos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 05:35:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`departamentos`, CONSTRAINT `departamentos_ibfk_1` FOREIGN KEY (`cod_region`) REFERENCES `regiones` (`cod_region`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (\'24\', \'Inventado\', \'9\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (\'24\', \'Inventado\', \'9\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (:cod_depto:, :nombre_depto:, :cod_region:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Departamentos.php(28): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Departamentos->agregarDepartamento()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departamentos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 05:35:47 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`departamentos`, CONSTRAINT `departamentos_ibfk_1` FOREIGN KEY (`cod_region`) REFERENCES `regiones` (`cod_region`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (\'24\', \'Inventado\', \'9\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (\'24\', \'Inventado\', \'9\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (\'24\', \'Inventado\', \'9\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `departamentos` (`cod_depto`, `nombre_depto`, `cod_region`) VALUES (:cod_depto:, :nombre_depto:, :cod_region:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Departamentos.php(28): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Departamentos->agregarDepartamento()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departamentos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 05:53:11 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`municipios`, CONSTRAINT `municipios_ibfk_1` FOREIGN KEY (`cod_depto`) REFERENCES `departamentos` (`cod_depto`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `mu...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `mu...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `mu...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mu...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Municipios.php(26): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Municipios->agregarMunicipio()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Municipios))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 05:53:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`municipios`, CONSTRAINT `municipios_ibfk_1` FOREIGN KEY (`cod_depto`) REFERENCES `departamentos` (`cod_depto`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: agregar_municipio]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (:cod_muni:, :nombre_municipio:, :cod_depto:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Municipios.php(26): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Municipios->agregarMunicipio()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Municipios))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 05:53:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`municipios`, CONSTRAINT `municipios_ibfk_1` FOREIGN KEY (`cod_depto`) REFERENCES `departamentos` (`cod_depto`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (\'99\', \'Municipio Inventado\', \'24\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (\'99\', \'Municipio Inventado\', \'24\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (:cod_muni:, :nombre_municipio:, :cod_depto:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Municipios.php(26): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Municipios->agregarMunicipio()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Municipios))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 05:53:11 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2024_ciudadanos`.`municipios`, CONSTRAINT `municipios_ibfk_1` FOREIGN KEY (`cod_depto`) REFERENCES `departamentos` (`cod_depto`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (\'99\', \'Municipio Inventado\', \'24\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (\'99\', \'Municipio Inventado\', \'24\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (\'99\', \'Municipio Inventado\', \'24\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `municipios` (`cod_muni`, `nombre_municipio`, `cod_depto`) VALUES (:cod_muni:, :nombre_municipio:, :cod_depto:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Municipios.php(26): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Municipios->agregarMunicipio()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Municipios))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 05:54:15 --> mysqli_sql_exception: Column 'cod_nivel_acad' cannot be null in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ni...', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ni...')
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ni...')
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ni...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\NivelesAcademicos.php(26): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\NivelesAcademicos->agregarNivelAcademico()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NivelesAcademicos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-07-20 05:54:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'cod_nivel_acad' cannot be null
[Method: POST, Route: agregar_nivel_acad]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (:cod_nivel_acad:, :nombre:, :descripcion:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NivelesAcademicos.php(26): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\NivelesAcademicos->agregarNivelAcademico()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NivelesAcademicos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 05:54:15 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'cod_nivel_acad' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (NULL, \'Post-grado prueba\', \'Inventado \')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (NULL, \'Post-grado prueba\', \'Inventado \')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (:cod_nivel_acad:, :nombre:, :descripcion:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NivelesAcademicos.php(26): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\NivelesAcademicos->agregarNivelAcademico()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NivelesAcademicos))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-20 05:54:15 --> [Caused by] mysqli_sql_exception: Column 'cod_nivel_acad' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (NULL, \'Post-grado prueba\', \'Inventado \')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (NULL, \'Post-grado prueba\', \'Inventado \')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (NULL, \'Post-grado prueba\', \'Inventado \')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `nivelesacademicos` (`cod_nivel_acad`, `nombre`, `descripcion`) VALUES (:cod_nivel_acad:, :nombre:, :descripcion:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NivelesAcademicos.php(26): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\NivelesAcademicos->agregarNivelAcademico()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NivelesAcademicos))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-20 22:35:28 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for sql305.infinityfree.com failed: Host desconocido.  in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 186)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('sql305.infinity...', 'if0_36935719', Object(SensitiveParameterValue), 'if0_36935719_fs...', 3306, '', 0)
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(11): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->index()
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for sql305.infinityfree.com failed: Host desconocido.  in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('sql305.infinity...', 'if0_36935719', Object(SensitiveParameterValue), 'if0_36935719_fs...', 3306, '', 0)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->index()
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for sql305.infinityfree.com failed: Host desconocido.  in C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\app\Controllers\Ciudadanos.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(933): App\Controllers\Ciudadanos->index()
#7 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
#8 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\fs2024\Ci-Ciudadanos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-07-20 22:35:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for sql305.infinityfree.com failed: Host desconocido. 
[Method: GET, Route: ver_ciudadanos]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ciudadanos`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Ciudadanos.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Ciudadanos->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ciudadanos))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
